### ISSUE TITLE
Running VINS-mono on bag files

### ISSUE THREAD

**Issue by amirmoeini** [mit-fast/Blackbird-Dataset#10]
Hi,

I am trying to get the VINS-mono working on one of your bag files but it seems the bag file doesn't contain an image topic!

Can you please clarify on this?

Thanks

**Comment by Winter-Guerra** [comment]
Hi there,

This question has already been asked here: https://github.com/mit-fast/Blackbird-Dataset/issues/9 . I'd recommend taking a look at the conversation there and trying out the quickstart in the README.

Best,
-Winter
