### ISSUE TITLE
Camera Extrinsic Calibration

### ISSUE THREAD

**Issue by vaibhavviswanathan** [mit-fast/Blackbird-Dataset#11]
Hi,

I get “Access Denied” when trying to download the camera calibration videos. Can we either
1. Get access to the calibration data or
2. Get access to the output Kalibr files
?

Thanks!

**Comment by Winter-Guerra** [comment]
Hi Vaibhav,

I've fixed the "Access Denied" issue for the calibration video files. Could you please try downloading them again? I'm terribly sorry for the inconvenience.

Best,
-Winter

**Comment by jaekelj** [comment]
Hi Winter,

Is it possible for you to provide a sample calibration file? For example, a calibration file that you've used to run on VINS-Fusion if you have it.

Thanks!

**Comment by varunmurali1** [comment]
closing this since it is the same as #12
