### ISSUE TITLE
HTTP 403 Error

### ISSUE THREAD

**Issue by p678m854** [mit-fast/Blackbird-Dataset#18]
Whenever you  try an access any of the pages associated with the dataset, you get a 403 error. Copy of the error message below. This has been going on since at least 17 March 2021.

```
403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)
Request ID: fNHVbTTIQ3cuo0lPCDI0Nqd2X64yozrvP6dJjun4pK2QITrMvReGDA==
```

**Comment by Winter-Guerra** [comment]
Hi there,

The dataset should be back online (http://blackbird-dataset.mit.edu/BlackbirdDatasetData/). We're terribly sorry for the wait, data migration between cloud providers took longer than expected.

Best,
-Winter
