### ISSUE TITLE
Dataset Access Denied 

### ISSUE THREAD

**Issue by chahatdeep** [mit-fast/Blackbird-Dataset#8]
Hi,

When following the instructions on the Blackbird dataset git page, I'm getting a message saying 'Access Denied' when it goes to AWS to download the 'loseless.mov' file. This is occurring in every sequence available.

**Comment by Winter-Guerra** [comment]
Hi Chahat,

You might see "Access Denied" messages for RGB, semantic, and depth camera data. These new camera feeds are part of an IJRR extension of the original Blackbird Dataset. The IJRR article is currently in press and will be released shortly.

Best,
-Winter

**Comment by juanmed** [comment]
Hi, I am also facing the same issue with the same sequences. Any updates?

**Comment by Winter-Guerra** [comment]
Hi there,

The dataset should be back online (http://blackbird-dataset.mit.edu/BlackbirdDatasetData/). We're terribly sorry for the wait, data migration between cloud providers took longer than expected.

@karnikram Some sequences were recovered during the data migration (such as http://blackbird-dataset.mit.edu/BlackbirdDatasetData/mouse/yawForward/maxSpeed5p0/NYC_Subway_Station_Moving_Train/ ), would you mind checking again to see if the sequences relevant to your research are available? 

Best,
-Winter
