### ISSUE TITLE
Instructions to generate a sequence

### ISSUE THREAD

**Issue by juanmed** [mit-fast/Blackbird-Dataset#9]
Hi,

While I thank the authors for sharing such an amazing dataset, I have been struggling in the past few days and not been able to generate a single sequence. I would like to end up with a single rosbag file that includes left,right image topics and the topics already included in the rosbag.bag for each sequence ( imu, pose_ref, pwm, rotor_rpm, state, camera_info, tf, etc) (similar to the Euroc rosbag files).

It is my perception that instructions in the front page would be helpful to myself and many others. I did tried to find instructions for this task in the README.md and issues, but was unsuccessful. 

Trying to generate a sequence, I first found that the rosbag.bag files do not contain the images. I proceeded to download this repository and build, as indicated in the instructions. Since I could not find instructions to somehow generate the left,right images, I found the `republish_images.launch` and launched. At that moment I also discovered I needed Flightgoggles, so I downloaded and built. However, I noticed I did not have the `blackbirdDatasetSensors.xml` file when the following error was raised:

```bash
while processing /home/fg_ws/src/flightgoggles/flightgoggles/config/sensors/blackbirdDatasetSensors.xml:
Invalid roslaunch XML syntax: [Errno 2] No such file or directory: u'/home/fg_ws/src/flightgoggles/flightgoggles/config/sensors/blackbirdDatasetSensors.xml'
The traceback for the exception was written to the log file
```

I looked for that file in this and Flightgoggles' repository but was not found anywhere, and find myself stuck at this point. 

This dataset is particularly useful since it contains pwm and rotor_rpm data, a  seldom seen feature. Could please any of the authors provide me clear instructions to build such a bag file as stated above?

Thank you!

**Comment by juanmed** [comment]
Hi,

Exploring the files, I found that in `agile` package imported in `msgConverters.py` is not present. Also, this does not seem to be a publicly available package. Also, the script `renderDatasetUsingROStoHEVC.py` calls a `blackbirdDataset.launch` file in flightgoggles rospackage. This launch file is also unavailable. 

Could you please indicate where are these files to be found?
 
Thanks.

**Comment by juanmed** [comment]
@Winter-Guerra  Apart from `blackbirdDatasetSensors.xml`, the node for `blackbird_publish_video_node`, both in `republish_images.launch` file, are missing. It seems that, if the missing files were present, this launch file would be enough to generate the bag file I am looking to get. Could you please share those files? Thanks.

**Comment by Winter-Guerra** [comment]
Hi Juan,

Thanks for your interest in the dataset! 

> I would like to end up with a single rosbag file that includes left,right image topics and the topics already included in the rosbag.bag for each sequence ( imu, pose_ref, pwm, rotor_rpm, state, camera_info, tf, etc) (similar to the Euroc rosbag files).

The BlackBird dataset differs slightly in form from the Euroc dataset. Namely, images are not stored directly in the rosbag.bag. The pre-rendered image streams are stored as HEVC video files. The reason for storing the images outside of the rosbag is so that researchers can mix and match camera types and also to decrease download size by leveraging HEVC compression.

To get you started with playing back a rosbag and receiving images, you should not need to run FlightGoggles. You can simply use the pre-rendered RGB camera sequences included in the dataset. 

Let me update the readme with an example and then I’ll ping you back.

Best,
-Winter

**Comment by juanmed** [comment]
Thanks for your answer. In the end it would be nice to have a method to play the data, in proper sequence, into rostopics. From there I can rosbag record or whatever.  Looking forward to your instructions. Thanks!

**Comment by Winter-Guerra** [comment]
Hi Juan,

I'm terribly sorry for the wait. I've updated the README with a quick start guide. The quick start guide uses Docker, but can be adapted for local use in a ROS environment. Please let me know what you think!

Best,
-Winter

**Comment by juanmed** [comment]
Hi,

Thanks for the updated instructions. I was trying the docker image and although I could follow all the instructions successfully, I am facing some issues with the rendered images. They are all noise and look like this (up: left gray, middle: left rgb, botton: right gray):

![blackbird_record](https://user-images.githubusercontent.com/21977733/79595688-4382cd80-811a-11ea-957d-a5651b7920e2.png)

Could you please confirm that you can actually render the correct RGB and grayscale images? Thanks.

Looking at the `publish_video_node.cpp` code I could not find any error. The only detail is that it seems to me that in the `playback_sequence.launch` file, the param `is_color` for RGB [L52](https://github.com/mit-fast/Blackbird-Dataset/blob/100f5a7b3d027350401a86fb405053123c0d2da0/ros_utilities/blackbird_dataset/launch/playback_sequence.launch#L52) camera should be set to 1, so that the correct formats are choosen.

**Comment by Winter-Guerra** [comment]
Ah, whoops. This looks like a stride / type conversion error in the OpenCV code. Let me dig into this further and get back to you.

**Comment by Winter-Guerra** [comment]
Okay, I fixed the issue. Please run `docker pull winterg/flightgoggles_ros:ijrr` *before* running the `docker run -it [...]` command in the README instructions.

**Comment by juanmed** [comment]
It is working now, thanks!
